# Generated by Django 5.0.6 on 2024-06-26 13:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultUber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gasto_por_km', models.FloatField()),
                ('gasto_com_comb', models.FloatField()),
                ('comb_com_desc', models.FloatField()),
                ('ganho_por_km', models.FloatField()),
                ('lucro', models.FloatField()),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
