# Generated by Django 5.0.6 on 2024-06-26 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultuber',
            options={'verbose_name': 'Resultado uber', 'verbose_name_plural': 'Resultados uber'},
        ),
    ]
