# Generated by Django 5.0.6 on 2024-06-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0002_alter_resultuber_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultuber',
            name='horas_trab',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultuber',
            name='km_rodado',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultuber',
            name='preco_comb',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultuber',
            name='data_criacao',
            field=models.DateField(),
        ),
    ]
