# Generated by Django 5.0.6 on 2024-06-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0003_resultuber_horas_trab_resultuber_km_rodado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultuber',
            name='ganho_hora',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
