# Generated by Django 5.0.6 on 2024-06-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0004_resultuber_ganho_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultuber',
            name='data_criacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
