# Generated by Django 5.0.6 on 2024-06-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0005_alter_resultuber_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultuber',
            name='km_rodado',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
