# Generated by Django 5.0.6 on 2024-06-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0006_alter_resultuber_km_rodado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultuber',
            name='data_criacao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='resultuber',
            name='horas_trab',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultuber',
            name='km_rodado',
            field=models.FloatField(),
        ),
    ]
