# Generated by Django 5.0.6 on 2024-06-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0007_alter_resultuber_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultuber',
            name='data_criacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
