# Generated by Django 5.0.6 on 2024-06-30 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0008_alter_resultuber_data_criacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultuber',
            name='ganho_hora',
        ),
    ]
