# Generated by Django 5.0.6 on 2024-06-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0010_alter_resultuber_horas_trab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultuber',
            name='horas_trab',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
