# Generated by Django 5.0.6 on 2024-06-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0011_alter_resultuber_horas_trab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultuber',
            name='data_criacao',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
