# Generated by Django 5.0.6 on 2024-06-30 14:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0012_alter_resultuber_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultuber',
            name='data_criacao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
