# Generated by Django 5.0.6 on 2024-07-01 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0013_alter_resultuber_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultuber',
            name='faturamento',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
