# Generated by Django 5.0.6 on 2024-07-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0014_resultuber_faturamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultuber',
            name='km_por_litro',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
