# Generated by Django 5.0.6 on 2024-07-01 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0015_resultuber_km_por_litro'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultuber',
            name='ganho_hora',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
