# Generated by Django 5.0.6 on 2024-07-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0016_resultuber_ganho_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultuber',
            name='desc_comb',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
