# Generated by Django 5.0.6 on 2024-07-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0017_resultuber_desc_comb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultuber',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data criação'),
        ),
    ]
