# Generated by Django 5.0.6 on 2024-09-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0022_alter_resultuber_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultuber',
            name='observacao',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
